config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # nest the attendings routes under events to allow you to pass @event in the url to controller
  resources :events do
    post 'create_invite', to: 'invites#create'
    delete 'destroy_invite', to: 'invites#destroy'
  end

  # nesting the attendings routes under event passed the event_id to controller in addition to the
  # manually entered hash values for event and user, which causes an error. Could resolve this?
  post 'create_attending', to: 'attendings#create'
  delete 'destroy_attending', to: 'attendings#destroy'

  # sets url /my_events to show user's events
  get 'my_events', to: 'users#show'

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attending.rb
class Attending < ApplicationRecord

  scope :confirmed, ->(event_id) { where(attended_event_id: event_id) }

  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  validates_presence_of :attendee_id, :attended_event_id
end

app/models/event.rb
class Event < ApplicationRecord
  # scope allows common queries to be defined herein and method names set
  scope :past_events, -> { where('date < ?', Time.zone.now) }
  scope :future_events, -> { where('date > ?', DateTime.now) }

  has_many :invites, dependent: :destroy
  has_many :attendings, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendings, dependent: :destroy
  belongs_to :creator, class_name: "User"
  
  validates :name, :location, :date, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates_presence_of :creator_id

end

app/models/invite.rb
class Invite < ApplicationRecord

  scope :received, ->(event_id, user_id) { where(event_id: event_id, invitee_id: user_id) }
 
  belongs_to :event
  belongs_to :inviter, class_name: 'User'
  belongs_to :invitee, class_name: 'User'

  validates_presence_of :event_id, :inviter_id, :invitee_id

end

app/models/user.rb
class User < ApplicationRecord
  scope :attending_event, ->(event_id) { self.attendings.where(attended_event_id: event_id).exists? }
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :invites, foreign_key: :inviter_id, dependent: :destroy
  has_many :invites, foreign_key: :invitee_id, dependent: :destroy
  has_many :attendings, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendings, dependent: :destroy
  # associates user_id with creator_id in events table and allows event.creator method
  has_many :events, foreign_key: :creator_id, class_name: "Event", dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController

  before_action :authenticate_user!

  # check the attending does not already exist
  def create
    if Attending.find_by(attending_params).nil?
      @attending = Attending.new(attending_params)

      respond_to do |format|
        if @attending.save
          format.html { redirect_to my_events_path, notice: "You are attending this event!" }
        else
          format.html { redirect_to my_events_path, alert: "An error occured." }
        end
      end
    else
      flash.alert = 'You are already attending.'
      redirect_to my_events_path
    end
  end

  # to prevent errors, check if record exists
  # check destroy worked and notify
  def destroy
    @attending = Attending.find_by(attending_params)
    if @attending.nil?
      flash.alert = "This event attendance does not exist"
    elsif @attending.destroy
      flash.notice = "You are no longer attending this event."
    else
      flash.alert = "Error - attendance was not deleted."
    end
    redirect_to my_events_path
  end
  
  private

  def attending_params
    params.permit(:attendee_id, :attended_event_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  # authorizing access to the events resource - only creator can access
  before_action :authorize_item, only: [:update, :edit, :destroy]

  def index
    @events = Event.all.order('created_at DESC')
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find_by(params[:id])
  end

  def update
    @event = Event.find_by(params[:id])
    if @event.nil?
      flash.alert = 'Event does not exist'
    elsif @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # check destroy worked and notify
  def destroy
    @event = Event.find_by(params[:id])
    if @event.nil?
      flash.alert = 'Event does not exist'
    elsif @event.destroy
      flash.notice = 'Event was deleted.'
    else
      flash.alert = 'Error - event was not deleted.'
    end
    redirect_to root_path, status: :see_other
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :description, :location, :date, :private)
  end

  def authorize_item
    unless @event.creator == current_user 
      redirect_to @event, alert: 'You are not authorized do that.'
    end
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!

  def create
    @invite = Invite.new(invite_params)

    respond_to do |format|
      if @invite.save
        format.html { redirect_to event_path(invite_params[:event_id]), notice: "Invite sent!" }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # to prevent errors, check if record exists
  # check destroy worked and notify
  def destroy
    @invite = Invite.find_by(invite_params)
    if @invite.nil?
      flash.alert = "This invite does not exist"
    elsif @invite.destroy
      flash.notice = "Invite removed."
    else
      flash.alert = "Error - invite was not deleted."
    end
    redirect_to my_events_path
  end
  
  private

  def invite_params
    # no require method here because I am not using an invite#new object above
    params.permit(:event_id, :invitee_id, :inviter_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # see Events model scopes :past_events, :future_events
  def show
    @created_events = current_user.events.all
    @attended_events = current_user.attended_events.past_events
    @attending_events = current_user.attended_events.future_events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attendeelist.html.erb
      <div class="column is-2">
        <h4 class="panel-heading">Attendees</h4>
            <div class="box">
              <article class="media">
                <div class="media-content">
                  <div class="content">
                    <% @event.attendees.each do | attendee |%>
                      <%= attendee.username %><br />
                    <% end %>
                  </div>
                </div>
              </article>
            </div>
      </div>
 

app/views/events/_feed.html.erb
<div class="column is-half">
    <% @events.each do | event |%>
      <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <strong>@<%= event.creator.username %></strong><br /> 
            <p>Event: <%= event.name %></p>
            <p>Location: <%= event.location %></p>
            <p>Date: <%= event.date %></p>
            <p>Details: <%= event.description %></p>
          </div>
          <% if user_signed_in? %>
            <nav class="level">
              <div class="level-left is-mobile">
                <%= link_to 'View', event %>
                <%= button_to 'Attend', class: 'level-item' do %>
                  <span class='icon'><i class='button is-info is-inverted' aria-hidden='true'></i></span>
                <% end %>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/events/_form.html.erb
  <%= simple_form_for(@event) do | f | %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      
      <div class="field">
        <div class="control">
          <%= f.input :name, 
                      label: 'Event Name', 
                      input_html: { class: 'input' }, 
                      wrapper: false, label_html: { class: 'label' },
                      required: true,
                      autofocus: true %>
        </div>
      </div>

      <div class="field">
        <div class="control">    
          <%= f.input :location, 
                      label: 'Event Location', 
                      input_html: { class: 'input' }, 
                      wrapper: false, label_html: { class: 'label' },
                      required: true %>
       </div>
      </div>

      <div class="field">
        <div class="control">  
          <%= f.input :date, 
                      label: 'Date & Time', 
                      input_html: { class: 'datetime' }, 
                      wrapper: false, label_html: { class: 'label' },
                      required: true %>
       </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :private, 
                      label: 'Private Event', 
                      input_html: { class: 'checkbox' }, 
                      wrapper: false, label_html: { class: 'label' } %>
       </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :description, 
                      label: 'Event Description', 
                      input_html: { class: 'textarea' },
                      wrapper: false, label_html: { class: 'label' }, 
                      placeholder: 'Tell us about your event...' %>
     </div>
      </div>

    </div>
  </div>
  <%= f.button :submit, class: 'button' %>
  <% end %>
</div>

app/views/events/_invitepane.html.erb
    <div class="columns">
      <div class="column is-full">
        <article class="panel">
          <p class="panel-heading">Send Invites</p>
          <div class="box">
            <article class="media">
              <div class="media-content">
                <div class="content">
                  <% User.all.order('username Asc').each do | user |%>
                    <% unless user.id == current_user.id %>
                      <div class="box invites">
                        <div>
                          <p><strong>@<%= user.username %></strong> - <%= user.email %></p>
                        </div>
                          <%# see Attending scope :confirmed %>
                          <% if user.attendings.confirmed(@event.id).exists? %>
                            <div>
                              <p>Status: User attending</p>
                            </div>
                          <% elsif %>
                          <%# see Invite scope :received %>
                            <% user.invites.received(@event.id, user.id).exists? %>
                              <%= link_to 'Rescind', event_destroy_invite_path(:event_id=> @event.id, :invitee_id=> user.id), 
                                  data: { turbo_method: "delete" }, class: 'button rescind' %>
                              <div>
                                <p>Status: Invite pending</p>
                              </div>   
                          <% else %>
                              <%= link_to 'Invite', event_create_invite_path(:event_id => @event.id, :invitee_id=> user.id, :inviter_id=> current_user.id), 
                                  data: { turbo_method: "post" }, class: 'button' %>
                          <% end %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </article>
          </div>
        </article>
      </div>
    </div>

app/views/events/_past.html.erb
<div class="column is-one-quarter">
  <h3 class="title is-3">Past Events</h3>
  <nav class="panel">
    <% @events.past_events.each do | event |%>
      <div class="panel-block">
        <p><%= event.date.strftime("%B")[0,3] %> &nbsp;</p>
        <p><%= event.date.year %> &nbsp; &nbsp;</p>
        <p> <%= link_to event.name, event %></p> 
      </div>
    <% end %>
  </nav>
</div>      
  

app/views/events/_upcoming.html.erb
<div class="column is-half">
 <h1 class="title is-1">Upcoming Events</h1>
    <% @events.future_events.each do | event |%>
      <article class="panel <%= ' is-info' if event.creator == current_user %>">
        <p class="panel-heading"><%= event.name %> - @<%=event.creator.username%></p>
        <div class="box">
          <article class="media">
          <div class="media-content">
            <div class="content">
              <% if event.private == true %>
                  <p><strong>Attendance:</strong>&nbsp; invite only</p>
                <% else %>
                  <p><strong>Attendance:</strong>&nbsp; anyone</p>
                <% end %>
              <p><strong>Location:</strong> <%= event.location %></p>
              <p><strong>Date:</strong> 
                <%= event.date.strftime("%B")[0,3] %>
                <%= event.date.strftime("%d") %>,
                <%= event.date.year %></p>
            </div>
              <nav class="level">
                <div class="level-left is-mobile">
                  <p><%= link_to 'View', event, class: 'button' %> &nbsp; &nbsp;</p>
                    <% if user_signed_in? %> 
                      <% if event.creator == current_user %>
                        <p><%= link_to 'Edit', edit_event_path(event), class: 'button' %>&nbsp; &nbsp;</p>
                        <%= link_to 'Delete', event_path(event),
                            class: 'button',
                            data: { turbo_method: :delete,
                                    turbo_confirm: "Click OK to confirm deleting this event." } %>
                      <% elsif %>
                        <% event.private == true && current_user.attended_event_ids.include?(event.id) %>
                          <%= link_to 'Withdraw', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), 
                              data: { turbo_method: "delete",
                                      turbo_confirm: "You will need a new invite to attend. Click OK to confirm withdrawing." }, 
                                      class: 'button' %>
                      <% elsif %>
                        <% event.private == false && !current_user.attended_event_ids.include?(event.id) %>
                        <%= link_to 'Attend', create_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), 
                                  data: { turbo_method: "post" }, class: 'button' %>
                      <% elsif%>
                        <% event.private == false %>
                        <%= link_to 'Withdraw', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), 
                              data: { turbo_method: "delete",
                                      turbo_confirm: "Click OK to confirm withdrawing." }, 
                                      class: 'button' %>
                      <% end %>
                    <% end %>
                </div>
              </nav>
          </div>
        </article>
        </div>
      </article>
    <% end %>
</div>

app/views/events/edit.html.erb
<section class='section'>
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
      <h2 class='title is-2'>Edit Event</h2>
      <%= render 'form', event: @event %>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<section class='section'>
  <div class="container">
    <div class="columns">
      <div class='column is-one-fifth'></div>
        <%= render 'upcoming' %>
        <%= render 'past' %>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<section class='section'>
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
      <h2 class='title is-2'>Create Event</h2>
      <%= render 'form', event: @event %>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<section class='section'>
  <div class="container">
    <div class="columns is-centered">
      
      <div class="column is-6">
        <h3 class="panel-heading"><%= @event.name %></h3>
          <div class="box">
            <article class="media">
              <div class="media-content">
                <div class="content">
                  <p><strong>Host:</strong> @<%= @event.creator.username %></strong><br /> 
                  <p><strong>Location:</strong> <%= @event.location %></p>
                  <p><strong>Date:</strong> <%= @event.date %></p>
                  <p><strong>Details:</strong> <%= @event.description %></p>
                  <% if @event.private == true %>
                    <p><strong>Attendance:</strong>&nbsp; invite only</p>
                  <% else %>
                    <p><strong>Attendance:</strong>&nbsp; anyone</p>
                  <% end %>
                </div>
                <nav class="level">
                  <div class="level-left is-mobile">
                    <% if user_signed_in? %> 
                      <% if @event.creator == current_user %>
                        <p><%= link_to 'Edit', edit_event_path(@event), class: 'button' %>&nbsp; &nbsp;</p>
                        <%= link_to 'Delete', event_path(@event),
                            class: 'button',
                            data: { turbo_method: :delete,
                                    turbo_confirm: "Click OK to confirm deleting this event." } %>
                      <% elsif %>
                        <% @event.private == true && current_user.attended_event_ids.include?(@event.id) %>
                          <%= link_to 'Withdraw', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id), 
                              data: { turbo_method: "delete",
                                      turbo_confirm: "You will need a new invite to attend. Click OK to confirm withdrawing." }, 
                                      class: 'button' %>
                      <% elsif %>
                        <% @event.private == false && !current_user.attended_event_ids.include?(@event.id) %>
                        <%= link_to 'Attend', create_attending_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id), 
                                  data: { turbo_method: "post" }, class: 'button' %>
                      <% elsif%>
                        <% @event.private == false %>
                        <%= link_to 'Withdraw', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id), 
                              data: { turbo_method: "delete",
                                      turbo_confirm: "Click OK to confirm withdrawing." }, 
                                      class: 'button' %>
                      <% end %>
                    <% end %>
                  </div>
                </nav>
              </div>
            </article>
          </div>
          <% if @event.creator == current_user %>
            <%= render 'invitepane' %>
          <% end %>
      </div>
      <%= render 'attendeelist' %>
   </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   
    <%# This is the website header bar  %>
    <nav class="navbar">
      <div class="navbar-brand">    
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class='title is-5'>Private Events</h1>
        <% end %>
      </div>

      
        
      <div class="navbar-item">          
        <div class='field is-grouped'>
          <% if user_signed_in? %>
            <p class='control'>
              <%= link_to 'Create Event', new_event_url, class: 'button is-info is-inverted' %>
            </p>
            <p class='control'>
              <%= link_to 'My Events', my_events_url, class: 'navbar-item' %>
            </p>
            <p class='control'>
              <%= link_to 'Profile', edit_user_registration_path, class: 'navbar-item' %>
            </p>
            <p>
              <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: "delete" }, class: 'navbar-item' %>
            </p>
          <% else %>
            <p class='control'>
              <%= link_to 'Log in', new_user_session_path, method: :get, class: 'navbar-item' %>
            </p>
            <p class='control'>
            <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-item' %>
            </p>
          <% end %>
        </div>
      </div>
        
     
    </nav>

    <%# these flash hashes are added per the Devise install recommendation %>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification is-light">      
        <p class="notice "><%= notice %></p> 
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class='notification is-danger global-notification is-light'>
        <p class='alert'><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_attended.html.erb
<div class="column is-one-third">
  <h3 class="title is-3">Past Events</h3>
  <% @attended_events.each do | event |%>
    <article class='panel is-success'>
      <p class="panel-heading"><%= event.name %></p>
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p><strong>Host:</strong> @<%= event.creator.username %><br/> 
              <p><strong>Location:</strong> <%= event.location %></p>
              <p><strong>Date:</strong> 
                <%= event.date.strftime("%B")[0,3] %>
                <%= event.date.strftime("%d") %>,
                <%= event.date.year %></p>
            </div>
              <nav class="level">
                <div class="level-left is-mobile">
                  <p><%= link_to 'View', event, class: 'button' %>&nbsp; &nbsp;</p>
                   <%= link_to 'Remove', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), 
                              data: { turbo_method: "delete",
                                      turbo_confirm: "Click OK to confirm withdrawing from this event." }, 
                                      class: 'button' %>
                </div>
              </nav>
            </div>
          </div>
      </article>
    </article>
  <% end %>
</div>

app/views/users/_attending.html.erb
<div class="column is-one-third">
  <h3 class="title is-3">Upcoming Events</h3>
  <% @attending_events.each do | event |%>
    <article class='panel is-warning'>
      <p class="panel-heading"><%= event.name %></p>
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p><strong>Host:</strong> @<%= event.creator.username %><br/> 
              <p><strong>Location:</strong> <%= event.location %></p>
              <p><strong>Date:</strong> 
              <%= event.date.strftime("%B")[0,3] %>
              <%= event.date.strftime("%d") %>,
              <%= event.date.year %></p>
            </div>
              <nav class="level">
                <div class="level-left is-mobile">
                  <p><%= link_to 'View', event, class: 'button' %>&nbsp; &nbsp;</p>
                   <%= link_to 'Withdraw', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), 
                              data: { turbo_method: "delete",
                                      turbo_confirm: "Click OK to confirm withdrawing from this event." }, 
                                      class: 'button' %>
                </div>
              </nav>
            </div>
          </div>
        </article>
    </article>
  <% end %>
</div>

app/views/users/_created.html.erb
<div class="column is-one-third">
 <h3 class="title is-3">My Events</h3>
    <% @created_events.each do | event |%>
    <article class='panel is-info'>
      <p class="panel-heading is-info"><%= event.name %></p>
        <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p><strong>Host:</strong> @<%= event.creator.username %><br/> 
              <p><strong>Location:</strong> <%= event.location %></p>
              <p><strong>Date:</strong> 
                <%= event.date.strftime("%B")[0,3] %>
                <%= event.date.strftime("%d") %>,
                <%= event.date.year %></p>
            </div>
              <nav class="level">
                <div class="level-left is-mobile">
                  <p><%= link_to 'View', event, class: 'button' %> &nbsp; &nbsp;</p>
                  <p><%= link_to 'Edit', edit_event_path(event), class: 'button' %>&nbsp; &nbsp;</p>
                  <%= link_to 'Cancel', event_path(event),
                      class: 'button',
                      data: 
                          {
                            turbo_method: :delete,
                            turbo_confirm: "Click OK to confirm cancelling this event."
                          } %>
                </div>
              </nav>
          </div>
        </article>
        </div>
      </article>
  <% end %>
</div>

app/views/users/_invites.html.erb
<div class="column is-4">
  <article class='panel is-danger'>
    <h4 class="panel-heading is-info">Invites</h4>
    <div class="box is-center">
      <article class="media">
        <div class="media-content">  
          <div class="content">
            <% current_user.invites.each do | invite |%>
              <div class='panel-block invites'>
                <h3><%= invite.event.name %>&nbsp;</h3>
                <%= link_to 'View', event_path(invite.event_id), class: 'button' %>
                <%if !current_user.attended_event_ids.include?(invite.event_id) %>
                  <%= link_to 'Attend', create_attending_path(:attendee_id=>current_user.id, :attended_event_id=>invite.event_id), 
                      data: { turbo_method: "post" }, class: 'button' %>
                <% end %>
                <%= link_to 'Clear invite', event_destroy_invite_path(:event_id=> invite.event_id, :invitee_id=> current_user.id), 
                              data: { turbo_method: "delete" }, class: 'button rescind' %><br />
              </div>
            <% end %>
          </div>   
        </div>
      </article>
    </div>  
  </div> 
</article>

app/views/users/show.html.erb
<% if current_user.invites.exists? %>
  <section class='section'>
    <div class="container">
      <div class="columns is-centered">
          <%= render 'invites' %>
      </div>
    </div>
  </section>
<% end %>

<section class='section'>
  <div class="container">
    <div class="columns">
        <%= render 'created' %>
        <%= render 'attending' %>
        <%= render 'attended' %>
    </div>
  </div>
</section>